name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Generate HTML from Markdown
        uses: ldeluigi/markdown-docs@latest
        with:
          src: .
          dst: html
          title: Guía como instalar KDE en Pop OS
          language: es
          hide-repository: true
      # https://github.com/docker/setup-qemu-action
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ewan1011/kdepopguide:latest
